### ISSUE TITLE
zypak-wrapper has no effect on CEF-based application

### ISSUE THREAD

**Issue by Adamcake** [refi64/zypak#34] opened 2023-07-20 18:04 UTC
Hopefully I'm just missing something obvious, but I added zypak to my flatpak which is here:
https://github.com/Adamcake/bolt-flatpak/
and it seems to have no effect at all. The error I get when running `zypak-wrapper /app/opt/bolt-launcher/bolt` is the same as if I were to run it directly, that being:

> [0720/181521.087150:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /app/opt/bolt-launcher/chrome-sandbox is owned by root and has mode 4755.

I've tried setting CHROME_WRAPPER correctly and changing ZYPAK_SPAWN_LATEST_ON_REEXEC but nothing's had any effect. (BTW, unrelated, your readme says ZYPAK_SPAWN_LATEST_ON_REEXEC defaults to true but it actually defaults to false - looks like this was changed in a recent commit 0a73ab0 and the readme hasn't been updated to match)

I use a custom build of CEF with the ungoogled-chromium patchset applied to it, which you can see in the repo. Looking at how zypak works I don't think that's relevant, but I mention it just in case.

I can post the output of ZYPAK_DEBUG=1 if you like but it didn't have anything particularly interesting in it, at least not to my eyes.

Hope you can help.

**Comment by refi64** [comment] 2023-07-21 01:10
> BTW, unrelated, your readme says ZYPAK_SPAWN_LATEST_ON_REEXEC defaults to true but it actually defaults to false

oops, should be fixed now.

As for the CEF issue, the linked manifest doesn't seem to use zypak-wrapper, could you show how it's being invoked in the repo?

> I use a custom build of CEF with the ungoogled-chromium patchset applied to it, which you can see in the repo. Looking at how zypak works I don't think that's relevant, but I mention it just in case.

Does the app *require* the custom CEF? I'd need to use the standard one for testing, since I'm on an arm64 host and thus need the arm64 binaries.

**Comment by Adamcake** [comment] 2023-07-21 01:26
I was testing with some local changes to the bolt and flatpak-bolt repos. If you're willing to clone them locally and change the .yml file to point to your local copy, then you'd want to change `./bolt` to `zypak-wrapper ./bolt` on line 17 of CMakeLists.txt. That line outputs the shell script that gets installed in bin; everything else goes in /opt.

> Does the app require the custom CEF?
Nope. I haven't tested with the official builds but there's no reason to think it shouldn't work.

**Comment by nmlynch94** [comment] 2023-07-21 01:49
Here is a repo with a reproducible example. You should just be able to build and run it https://github.com/nmlynch94/bolt-flatpak.

**Closed** 2023-07-21 23:08 UTC

**Comment by refi64** [comment] 2023-07-21 23:10
Okay I *think* this should be fixed, with c7daf0c I can now run the Bolt flatpak by setting `ZYPAK_CEF_LIBRARY_PATH=/app/opt/bolt-launcher/libcef.so`. (Amusingly enough I also found a bug in CEF's CMake scripts on arm64 Linux :sweat_smile: need to fix that later on...)
