### ISSUE TITLE
Handling electron.relaunch()

### ISSUE THREAD

**Issue by dbrgn** [refi64/zypak#26] opened 2022-09-16 15:05 UTC
When calling `electron.app.relaunch()` followed by `electron.app.exit()`, Electron should restart: https://www.electronjs.org/docs/latest/api/app#apprelaunchoptions This works fine in a standalone binary, but fails to restart in Flatpak.

I assume Electron stores the path and args on start, and then launches a new detached process followed by exiting. This way, zypak will exit (because the child process has terminated) and Flatpak will exit as well (because zypak is the entrypoint script). (Here's the Electron relaunch implementation: https://github.com/electron/electron/blob/19baea4bc2be42ac0568bacab9e7365bb3f8ce26/shell/browser/api/electron_api_app.cc#L1152-L1186)

I saw that zypak has `ZYPAK_SPAWN_LATEST_ON_REEXEC`, but that seems to be something different, right?

Is there a way to get relaunching to work (including a properly set up sandbox) with zypak as launcher / entrypoint?

**Comment by refi64** [comment] 2023-02-11 00:55
This should be fixed in the latest beta.

**Closed** 2023-02-11 00:54 UTC

**Comment by ShGKme** [comment] 2026-01-23 09:57
Work for us in neither `v2024.01.17` nor `v2025.09`...

```ts
app.relaunch()
app.exit(0)
```

Is the fix still actual?
Does it require any additional steps in the app?

**Comment by ShGKme** [comment] 2026-01-23 13:32
Apparently, this works (which is supposed to be the same?):
```ts
app.relaunch({ args: process.argv.slice(1) })
```
Moreover, `process.argv` is empty except for argv[0] path.

Tested with Electron 38, 39, 40.

The problem is only reproducible with Flatpak.
